# Generated by Django 4.0.2 on 2022-02-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="price",
        ),
    ]
